### PR TITLE
fixed table width issues on filtering page

### PR DESCRIPTION
**Pull request by rebeja**
https://rebeja.github.io/imhotep/docs/filtering/

### CODE REVIEW

**Comment by sjacobs-indeed** [comment]
Nice work @rebeja ! I tested this page on my mobile device and it scrolls horizontally. 

Does this need to be done for every table on the site?

**Comment by rebeja** [comment]
Good call @sjacobs-indeed , I updated the formatting on the rest of the tables.

**Comment by rebeja** [comment]
@sjacobs-indeed what do you think of making the sidebar nav collapsible?

**Comment by sjacobs-indeed** [comment]
Thank you for updating each table. Where would I see the collapsible nav bar? I think having a collapsible nav bar is a decision for the OSS team.

**Comment by rebeja** [comment]
> Thank you for updating each table. Where would I see the collapsible nav bar? I think having a collapsible nav bar is a decision for the OSS team.
@sjacobs-indeed 

It displayed when I ran it locally but it isn't appearing on the preview site  ¯\_(ツ)_/¯ 

I thought it might be a solution for this, from the TW ticket: "Also, across all these docs, we should really hide the TOC somehow on mobile devices. It moves all the page content below the fold." 

I'm ok with just resolving the table fixes and passing this part on to the OSS team.

**Comment by sjacobs-indeed** [comment]
How about creating a separate ticket for the left-hand nav and asking an OSS team engineer for help / guidance on what they prefer?

**Pull request merged**
